[lotus]
client_api_url="http://[ip]:[port]/rpc/v0"   # Url of lotus client web api, generally the [port] is 1234
market_api_url="http://[ip]:[port]/rpc/v0"   # Url of lotus market web api, generally the [port] is 2345, when market and miner are not separate, it is also the url of miner web api
market_access_token=""                       # Access token of lotus market web api, when market and miner are not separate, it is also the access token of miner web api