[pokt]
pokt_api_url="http://[ip]:[port]/v1"          # Url of pocket client web api, generally the [port] is 8081
pokt_access_token=""                          # Access token of pocket network api
pokt_address=""                               #
pokt_docker_image="filswan/pocket:RC-0.9.0"   #
pokt_docker_name="pokt-node"                  #
pokt_config_path="/root/.pocket"              #
pokt_scan_interval=600                        #
pokt_server_api_url="http://127.0.0.1:8088/"  #
pokt_server_api_port=8088                     #
