[pokt]
pokt_api_url="http://[ip]:[port]/v1"          # Url of pocket client web api, generally the [port] is 8081
pokt_access_token=""                          # Access token of pocket network api
pokt_docker_image="filswan/pocket:RC-0.9.0"   # Docker image name and version
pokt_docker_name="pokt-node"                  # Pocket containner name
pokt_config_path="/root/.pocket"              # Pocket chain blocks data path
pokt_scan_interval=600                        # Pocket scan interval
pokt_server_api_url="http://127.0.0.1:8088/"  # Url of pocket server api
pokt_server_api_port=8088                     # Port of pocket server api
